---
- name: Manage SMAK AM Lifecycle
  hosts: all
  become: yes
  become_method: runas
  # Win_Share_User is mapped from the PE Custom Credential
  become_user: "VA\VHAV06HTMAAP"
  become_flags: "logon_type=new_credentials"
  vars:
    uninstall: false
    smak_path: 'C:\_SMAK_AM'
    smak_share: '\\htm-mdus.med.va.gov\public\02_SMAK_AM_Install\_SMAK_AM\'

  tasks:
    # --- UNINSTALL BLOCK ---
    - name: Perform Uninstallation
      when: uninstall | bool
      block:
        - name: Run Removal script
          # Using .\ indicates local directory execution in the chdir
          ansible.windows.win_shell: '.\___4_Remove_SMAK2_Scheduled_Task.bat'
          args:
            chdir: '{{ smak_path }}'
          register: removal_result
          failed_when:
            - removal_result.rc != 0
            - '"path not found" not in removal_result.stderr | lower'

        - name: Remove SMAK directory
          ansible.windows.win_file:
            path: '{{ smak_path }}'
            state: absent

        - name: Stop Playbook Execution for Uninstalled Nodes
          meta: end_host

    # --- INSTALLATION BLOCK ---
    - name: Ensure the destination directory exists
      ansible.windows.win_file:
        path: '{{ smak_path }}'
        state: directory

    - name: Copy _SMAK_AM directory from network share
      ansible.windows.win_copy:
        src: '{{ smak_share }}'
        dest: '{{ smak_path }}\'
        remote_src: yes

    - name: Unblock SMAK files to prevent execution issues
      ansible.windows.win_powershell:
        script: |
          if (Test-Path '{{ smak_path }}') {
              Get-ChildItem -Path '{{ smak_path }}' -Recurse | Unblock-File
          }

    - name: Install SMAK2 Scheduled Task script
      ansible.windows.win_shell: '.\___3_Install_SMAK2_Scheduled_Task.bat'
      args:
        chdir: '{{ smak_path }}'

    - name: Manual Run SMAK2 script
      ansible.windows.win_shell: '.\___1_Manual_Run_SMAK2.bat'
      args:
        chdir: '{{ smak_path }}'
